
[project]
name = "stock-market-dashboard"
version = "2020.0.0"
dependencies = [
    "pytz",
    "python-dotenv",
    "polygon-api-client",
    "matplotlib",
    "flask-restful",
    "flask",
    "flask_cors",
    "pandas",
    "requests",
    "yfinance",
    "nltk",
    "vaderSentiment",
    "scikit-learn",
    "scipy",
    "numpy",
]
requires-python = ">=3.10"
authors = [
    { name = "Anshika Singh" },
    { name = "Colin Berry" },
    { name = "Dylan Myers" },
]

[tool.setuptools]
package-dir = { "" = "." }

[tool.setuptools.packages.find]
where = ["."]
include = ["TechnicalAnalysis*", "Signals*"]
